                                    # VALUE, KEY AND ITEMS OF DIC
                                
gem = {'1st':'ruby', '2nd':'diamond', '3':'garnet'}

for v in gem.values():              # to check the values in the dic...
    print(v)


for i in gem.items():               # to check all the items in the dic...
    print(i)

for k in gem.keys():                # to check all the keys in the dic...
    print(k)























